services:
  - type: web
    name: spicecraft-backend
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python seed_data.py
    startCommand: python manage.py migrate && python seed_data.py && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,msrrayalaseemaruchulu.com,www.msrrayalaseemaruchulu.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://msrrayalaseemaruchulu.com,https://www.msrrayalaseemaruchulu.com,http://localhost:5173,https://restaurant-app-frontend-n4mn-o0746ezp2.vercel.app,https://msrrayalaseemaruchulu.vercel.app,https://restaurant-frontend-one-mu.vercel.app
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 874943552282-inuauad2ma5il7e1mlkv93jrbhlfe92l.apps.googleusercontent.com
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
